# DYNAMIC vim plugins list

[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_i = 1
hook_source = '''
  let g:python3_host_prog = '/usr/bin/python3'
  let g:deoplete#enable_at_startup = 1
'''

# [[plugins]]
# repo = 'scrooloose/nerdtree'

# [[plugins]]
# repo = 'Xuyuanp/nerdtree-git-plugin'
# depends = ['nerdtree']
# on_event = ['VimEnter']
# hook_post_source = 'NERDTree'
